databases:
  - name: awesomelink
    databaseName: awesomelink
    user: tterb

services:
  - type: web
    name: awesomelink
    env: python
    buildCommand: "./bin/build.sh"
    startCommand: "gunicorn awesomelink.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: awesomelink
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4