# Generated by Django 3.2.4 on 2021-06-18 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwesomeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=900, validators=[django.core.validators.URLValidator])),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
