# Generated by Django 3.2.4 on 2021-06-19 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomelink',
            name='normalized_url',
            field=models.CharField(default='0', max_length=900),
        ),
        migrations.AlterField(
            model_name='awesomelink',
            name='url',
            field=models.CharField(max_length=900, unique=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
