# Generated by Django 3.2.4 on 2021-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_awesomelink_normalized_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomelink',
            name='flag_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
