# Generated by Django 3.2.4 on 2021-06-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_awesomelink_isapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awesomelink',
            old_name='isApproved',
            new_name='is_approved',
        ),
    ]
