# Generated by Django 3.2.4 on 2021-06-23 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_rename_isapproved_awesomelink_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awesomelink',
            name='url',
            field=models.URLField(max_length=900, unique=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
