# Generated by Django 3.2.4 on 2021-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_auto_20210626_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomelink',
            name='is_embeddable',
            field=models.BooleanField(default=False),
        ),
    ]
