# Generated by Django 3.2.4 on 2021-08-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_awesomelink_is_embeddable'),
    ]

    operations = [
        migrations.AddField(
            model_name='awesomelink',
            name='is_secure',
            field=models.BooleanField(default=False),
        ),
    ]
